
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"
[[mods]] #mandatory
# The modid of the mod
modId="harvestseason" #mandatory
version = "${version}"
displayName="Harvest Season" #mandatory
logoFile="icon.png" #optional
credits="MehVahdJukaar, Plantkillable" #optional
authors="MehVahdJukaar, Plantkillable" #optional

description='''
Pumpkin carving and Corn
'''
displayURL="https://www.curseforge.com/minecraft/mc-mods/harvest-saason" #optional
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/harvest-saason/issues" #optional
itemIcon="harvestseason:corn" #catalogue icon

configuredBackground= "minecraft:textures/block/jack_o_lantern.png"

[[dependencies.harvestseason]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.harvestseason]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.harvestseason]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.19.2-2.0.28,]"
    ordering="NONE"
    side="BOTH"
